version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8888:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info -B"

  flower:
    image: mher/flower:0.9.7
    depends_on:
      - redis
    ports:
      - "5555:5555"
    restart: on-failure
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']